plays:
  - name: 安装nginx
    hosts: app
    tasks:
      - name: 创建soft目录
        tags: 
          - soft
          - home
        shell: |
          sudo mkdir -p "{{.soft.home}}"
          sudo chown -R app:app "{{.soft.home}}"
      - name: 上传nginx安装包
        tags: nginx
        upload:
          src: soft/nginx.zip
          dest: "{{.soft.home}}"
      - name: 安装 nginx 依赖
        tags:
          - nginx
          - install
        shell: |
           cd "{{.soft.home}}"
           sudo unzip nginx.zip
           cd nginx
           sudo unzip gcc.zip
           sudo rpm -Uvh --force --nodeps gcc/*rpm
           sudo unzip gcc-c++.zip
           sudo rpm -Uvh --force --nodeps gcc-c++/*rpm
           sudo tar -zxf pcre-8.35.tar.gz
           cd pcre-8.35/
           sudo ./configure
           sudo make & make install
           cd "{{.soft.home}}"/nginx
           sudo tar -zxf libtool-2.4.2.tar.gz
           cd libtool-2.4.2
           sudo ./configure
           sudo make & make install
      - name: 安装nginx
        tags:
          - nginx
          - install
        shell: |
           cd "{{.soft.home}}"/nginx
           sudo tar -xvf nginx-1.22.0.tar.gz
           cd nginx-1.22.0
           sudo ./configure --prefix=/usr/local/nginx
           sudo make & make install
      - name: 复制nginx配置文件
        tags:
          - nginx
          - conf
        template:
          src: soft/nginx-iotplat.conf
          dest: /usr/local/nginx/conf/nginx-iotplat.conf     
      - name: 上传nginx的service
        tags:
          - nginx
          - service
        upload:
          src: service/nginx.service
          dest: /lib/systemd/system/
      - name: nginx自启动
        tags:
          - nginx
          - service
        shell: |
          sudo systemctl daemon-reload
          sudo systemctl enable nginx
          sudo systemctl start nginx
          sudo firewall-cmd --permanent --add-port=8888/tcp --zone=public
          sudo firewall-cmd --reload       