plays:
  - name: 安装node
    hosts: app
    tasks:
      - name: 安装node依赖
        tags: node
        shell: |
          sudo yum install -y npm
          sudo npm install -g n
          sudo n 13.0.1
          sudo mkdir -p /opt/lib/
          cd /opt/lib
          npm i --registry='https://registry.npm.taobao.org' puppeteer express mustache-express mathjs
          sudo yum install -y --allow --no-install-recommends fonts-wqy-microhei ttf-wqy-zenhei