plays:
  - name: 安装Redis数据库
    hosts: db
    tasks:
      - name: 创建soft目录
        tags: 
          - soft
          - home
        shell: |
          sudo mkdir -p "{{.soft.home}}"
          sudo chown app:app "{{.soft.home}}" 
      - name: 创建数据库数据目录
        tags: 
          - db
          - data
        shell: |
          sudo mkdir -p "{{.data.home}}"
          sudo chown app:app "{{.data.home}}"
      - name: 上传redis安装文件
        tags:
          - redis
          - upload
        upload:
          src: soft/redis-6.2.6.tar.gz
          dest: "{{.soft.home}}"
      - name: 编译安装redis
        tags:
          - redis
          - make
        shell: |
            cd "{{.soft.home}}"
            sudo tar -xvf redis-6.2.6.tar.gz
            cd "{{.soft.home}}"/redis-6.2.6
            sudo make
      - name: 上传redis的service文件
        tags:
          - redis
          - conf
          - service
        template:
          src: service/redis.service
          dest: /etc/systemd/system/redis.service
      - name: 配置redis
        tags:
          - redis
          - conf
        shell: |
            sudo mkdir -p {{.data.home}}/redis
            sudo chown -R app:app {{.data.home}}/redis
            sed -i 's#^bind 127.0.0.1#bind 0.0.0.0#g' {{.soft.home}}/redis-6.2.6/redis.conf
            sed -i 's#^dir ./#dir {{.data.home}}/redis/#g' {{.soft.home}}/redis-6.2.6/redis.conf
            sed -i 's#^notify-keyspace-events ""#notify-keyspace-events "Ex"#g' {{.soft.home}}/redis-6.2.6/redis.conf
            sed -i 's/# requirepass foobared/requirepass {{.redis.passwd}}/g' {{.soft.home}}/redis-6.2.6/redis.conf
            sudo systemctl daemon-reload
            sudo systemctl enable redis
            sudo systemctl start redis
            sudo firewall-cmd --permanent --add-port=6379/tcp --zone=public
            sudo firewall-cmd --reload