plays:
  - name: 安装zookeeper
    hosts: app
    tasks:
      - name: 创建soft目录
        tags: 
          - soft
          - home
        shell: |
          sudo mkdir -p "{{.soft.home}}"
          sudo chown -R app:app "{{.soft.home}}"
      - name: 上传zookeeper安装文件
        tags: zookeeper
        upload:
          src: soft/apache-zookeeper-3.8.1-bin.tar.gz
          dest: "{{.soft.home}}"
      - name: 安装zookeeper
        tags:
          - zookeeper
          - profile
        shell: |
          cd {{.soft.home}}
          sudo tar -zxf "{{.soft.home}}"/apache-zookeeper-3.8.1-bin.tar.gz
          sudo cp "{{.soft.home}}"/apache-zookeeper-3.8.1-bin/conf/zoo_sample.cfg "{{.soft.home}}"/apache-zookeeper-3.8.1-bin/conf/zoo.cfg
      - name: 上传zookeeper服务脚本
        tags:
          - zookeeper
          - service
        template:
          src: service/zookeeper.service
          dest: /etc/systemd/system/zookeeper.service          
      - name: zookeeper自启动
        tags:
          - zookeeper
          - service
        shell: |
          sudo systemctl daemon-reload
          sudo systemctl enable zookeeper
          sudo systemctl start zookeeper
          sudo firewall-cmd --permanent --add-port="{{.zookeeper.port}}"/tcp --zone=public
          sudo firewall-cmd --reload             